# Generated by Django 3.1.2 on 2020-12-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToASCII', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media/67851928627.jpg'),
        ),
    ]
