# Generated by Django 3.1.2 on 2020-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToASCII', '0002_auto_20201210_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
