# Generated by Django 3.1.2 on 2020-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToASCII', '0004_auto_20201212_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='source/'),
        ),
    ]
